[mypy]
python_version = 3.12

warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
disallow_untyped_decorators = False
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_no_return = True
warn_unreachable = True
strict_equality = True
show_error_codes = True

exclude = build/,dist/,venv/,.venv/,migrations/,alembic/

[mypy-boto3.*]
ignore_missing_imports = True

[mypy-jose.*]
ignore_missing_imports = True

[mypy-jsonschema.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-docker.*]
ignore_missing_imports = True

[mypy-testcontainers.*]
ignore_missing_imports = True

[mypy-order_service.presentation.main]
disable_error_code = arg-type

[mypy-order_service.presentation.middleware.http_middleware]
disable_error_code = no-any-return

[mypy-order_service.infrastructure.security.jwt]
disable_error_code = no-any-return

[mypy-order_service.infrastructure.messaging.sqs_publisher]
disable_error_code = no-any-return
